name: Deploy Site

# - Publish to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          token: ${{ secrets.BUILD_TOKEN }}
          branch: gh-pages
          folder: .